### Buscar pacotes do AUR
GET https://aur.archlinux.org/rpc/v5/search?arg=firefox&type=search
Accept: application/json


### Firefox
GET https://archlinux.org/packages/extra/x86_64/firefox/json
Accept: application/json

###teste
GET https://aur.archlinux.org/rpc/v5/info/nvim-lazy
Accept: application/json


###buscar pacman
GET https://archlinux.org/packages/search/json/?q=firefox
Accept: application/json